// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knulustsdmfhnwykhbqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtudWx1c3RzZG1maG53eWtoYnFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNjE0OTksImV4cCI6MjA2OTYzNzQ5OX0.xfKRPPPRzPr1BS3pt9CsgmtjsIChMSveFKpXnA3CvMw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});